# Generated by Django 3.1 on 2020-08-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'banks',
                'managed': True,
            },
        ),
    ]
